### ISSUE TITLE
The footnotes extension does not work when the superscript extension is enabled

### ISSUE THREAD

**Issue by gjtorikian** [kivikakk/comrak#272] opened 2023-01-17 20:43 UTC
As reported in https://github.com/gjtorikian/commonmarker/issues/217. If there's a file called test.txt:

```
Gimme footnote[^1]
This is ^superscript^

[^1]: Here is the footnote
```

`cargo run -- -e footnotes,superscript test.txt` produces:

```html
<p>Gimme footnote[^1]
This is <sup>superscript</sup></p>
```

whereas `cargo run -- -e footnotes test.txt` produces:

```
<p>Gimme footnote<sup class="footnote-ref"><a href="#fn1" id="fnref1">1</a></sup>
This is ^superscript^</p>
<section class="footnotes">
<ol>
<li id="fn1">
<p>Here is the footnote <a href="#fnref1" class="footnote-backref">↩</a></p>
</li>
</ol>
</section>
```

**Comment by kivikakk** [comment] 2023-01-22 02:02
Duplicate of #106.

**Closed by kivikakk** 2023-01-22 02:02 UTC
